src/NLog.Targets.ElasticSearch.Tests/App.config
src/NLog.Targets.ElasticSearch.Tests/ElasticSearchTargetTests.cs
src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs

Add a new option to include all event properties.

Added an option to include all log properties.

---

src/NLog.Targets.ElasticSearch.Tests/App.config
src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/IElasticSearchTarget.cs

For cases when ElasticSearch is hidden behind nginx with BasicAuth and https

Add BasicAuth support

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs

<target name="elasticSearch" xsi:type="BufferingWrapper" flushTimeout="5000">
<target name ="ElasticHoppsGroup"  xsi:type="ElasticSearch"
uri="http://xxxx.spir.fr:9200/"
index="mobilite-${date:format=yyyy.MM.dd}"
documentType="logevent"
disableAutomaticProxyDetection="true"
throwExceptions="True"/>
</target>

add DisableAutomaticProxyDetection property for bypass bluecoatproxy

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs

Pipeline parameter for preprocessing log messages by [Ingest node](https://www.elastic.co/guide/en/elasticsearch/reference/master/ingest.html) and [pipeline](https://www.elastic.co/guide/en/elasticsearch/reference/master/pipeline.html)

Pipeline parameter for Elasticsearch ingestion 

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs

Reverts ReactiveMarkets/NLog.Targets.ElasticSearch#32

Revert "Pipeline parameter for Elasticsearch ingestion "

---

src/NLog.Targets.ElasticSearch.Tests/NLog.Targets.ElasticSearch.Tests.csproj
src/NLog.Targets.ElasticSearch.Tests/packages.config
src/NLog.Targets.ElasticSearch/NLog.Targets.ElasticSearch.csproj
src/NLog.Targets.ElasticSearch/packages.config

ElasticSearch 5.2.0 & NLog 4.4.3

Upgrade packages

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs

Fixes spelling mistake for comment.

Fix spelling error

---

src/NLog.Targets.ElasticSearch.Tests/NLog.Targets.ElasticSearch.Tests.csproj
src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/NLog.Targets.ElasticSearch.csproj

According comments in this PR https://github.com/ReactiveMarkets/NLog.Targets.ElasticSearch/pull/51

Support for netstandard 1.5 & 2.0

---

src/NLog.Targets.ElasticSearch/StringExtensions.cs

A really small modification to be able to send full objets to elastic (same way as exception is sent).

Added support for raw json

---

src/NLog.Targets.ElasticSearch.Tests/NLog.Targets.ElasticSearch.Tests.csproj
src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/NLog.Targets.ElasticSearch.csproj

(and reduced allocations)
Resolves #54 and resolves #53

Fixed logging not working, when not writing in batches

---

README.md

Added NuGet Badge where the version number gets updated automatically.
Would be nice if the AppVeyor badge also links to the AppVeyor project.

Added NuGet Badge

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/NLog.Targets.ElasticSearch.csproj
src/NLog.Targets.ElasticSearch/StringExtensions.cs

InternalLogger includes Exception-details. Reduced nuget-dependencies for NetCore

Added support for layout in Uri

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/ExpandoObjectExtensions.cs
src/NLog.Targets.ElasticSearch/StringExtensions.cs

Attempt not to clone ExpandoObject and reuse JsonSerializer

Fields with object-type should be optimistic about not creating clones

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs

Resolves #80 by allowing use of `${configsetting}` or  `${environment}`

Added support for Layout in Username and Password

---

.github/lock.yml
.github/pull_request_template.md
.github/stale.yml
.vscode/launch.json
.vscode/tasks.json
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

Adding docs for open source maintenance.

build(github): adding lock and stale bots

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/IElasticSearchTarget.cs

Proxy support added

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/JsonToStringConverter.cs

feat: skip jsonserialize the entire world when meeting deep reflection types

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs

Trying to resolve #123 by not having DocumentType as required (can be blank).
https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html
Also improved the ability for getting debug-output into NLog InternalLogger (When enabled)
Also change the default-value from "logevent" to "_doc" as it seems to work better (also for Serilog)

feat: DocumentType (_type) has been deprecated in ElasticSearch 7

---

src/NLog.Targets.ElasticSearch.Tests/IntegrationTests.cs
src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs

Now you can do this:
```
<extensions>
<add assembly="NLog.Targets.ElasticSearch"/>
<add assembly="Elastic.CommonSchema.NLog"/>
</extensions>
<targets>
<target xsi:type="ElasticSearch" enableJsonLayout="true">
<layout xsi:type="EcsLayout" />
</target>
</targets>
```
Resolving #122

feat: EnableJsonLayout for using NLog Layout for generating document

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs

feat: Added option OpCodeCreate to support Elastic data streams

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/IElasticSearchTarget.cs

feat: add support for ApiKeyAuthenticationCredentials

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs

Added more logging to better diagnose the cause for issues like #142

feat: Include additional DebugInformation when failing with exception
