markmcdowell/NLog.Targets.ElasticSearch

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/NLog.Targets.ElasticSearch.csproj

Convert the Exception object to a string so that it doesn't break when being serialized by SimpleJson.
Only add fields if they render non empty values.
Change default index name to match the official logstash format.
Add some error handling.

Support using a connectionstring name for config.

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs

I've been talking to a guy on the ElasticSearch dev team and they don't recommend using the sniffing connection pool unless you have a really large deployment of unknown nodes. We have also been having some problems with it.

Change to use static connection pool and allow more than 1 host in the connection string.

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/NLog.Targets.ElasticSearch.csproj

Added ability to throw exception when bulking documents to elasticsearch in order to use ElasticSearchTarget within [FallbackGroup target](https://github.com/NLog/NLog/wiki/FallbackGroup-target).

Flag ThrowExceptions is added to support FallbackGroup target

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs

I got an exception in the SendBatch method where the result was a failure but there was no OriginalMessage in the result. This caused an exception which was subsequently caught, but was very difficult to debug and required getting the source code.
I also added a Trace level log to show the result during a failure. I am unsure as to whether this increases the chance of leaking information but it would have helped me debug the issue. Let me know if you don't like how this logging is occurring.

Added check for null OriginalException during failure to send batch.

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/NLog.Targets.ElasticSearch.csproj
src/NLog.Targets.ElasticSearch/packages.config

FallbackGroup issue : If bulk insert operation throws an exception, than this exception is logging but not rethrowing again. This was cousing NLog not to perform a log operation to next target when using in a FallbackGroup.
json serialization issue: this bug is on elasticsearch-net site but can be fixed temporarly. See details https://github.com/elastic/elasticsearch-net/issues/2052

Fixed: FallbackGroup and json serialization bug(temporary)

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs

Using `JsonConvert.Serialize` to serialize the exception could cause an exception:
> Self referencing loop detected for property 'Module' with type 'System.Reflection.RuntimeModule'. Path 'TargetSite.Module.Assembly.EntryPoint'.
This is prevented by setting `ReferenceLoopHandling` to `Ignore`.

Ignore self referencing loops

---

src/NLog.Targets.ElasticSearch/NLog.Targets.ElasticSearch.csproj

Fit to the newest NLog changes for Core 2.0 to use NLog version 4.5
Details are here https://github.com/NLog/NLog.Extensions.Logging/issues/155

Make compatible to the latest NLog changes

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/NLog.Targets.ElasticSearch.csproj
src/NLog.Targets.ElasticSearch/StringExtensions.cs

Resolves #49 for platforms not supporting FileWatcher.
Resolves #68 by re-adding pipeline support (Reverted in #33). Now it only adds Pipeline when it is configured.
Improves error-logging by not rethrowing exceptions, as it will affect original stacktrace.
Updated to Elasticsearch.Net ver. 6.1.0 and added support for setting config parameters `DisablePing` and `EnableHttpCompression`

Added support for Pipeline, only published when configured

---

src/NLog.Targets.ElasticSearch.Tests/App.config
src/NLog.Targets.ElasticSearch.Tests/NLog.Targets.ElasticSearch.Tests.csproj
src/NLog.Targets.ElasticSearch/NLog.Targets.ElasticSearch.csproj
src/NLog.Targets.ElasticSearch/StringExtensions.cs

…and hence updated dependencies to require .Net4.7.2.

Upgrade to Elasticsearch.Net 7.0.0. This depends on net-standard2.0

---

.editorconfig
src/NLog.Targets.ElasticSearch.Tests/IntegrationTests.cs
src/NLog.Targets.ElasticSearch.Tests/TestOutputTextWriter.cs
src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs

Hi,
We've come across an issue with the ElasticSearch target where, if we attempt to log an entry with an exception attached, and that exception has a property that can't be fetched due to throwing an exception, that causes the log message (or in fact an entire batch of log messages, if buffering is involved) to be lost.
This PR contains a change that means that properties causing errors while serializing are skipped instead of throwing an exception, and instead a warning is logged to the NLog internal log. It also avoids doing exception serialization at all if there is a custom field configured for exceptions.

Exceptions with properties that throw an exception when fetched fail to log

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/IElasticSearchTarget.cs

Adds support for cloud id connection pool.
Things to note: username and password authentication is required when using cloud id connection pool but I haven't checked that they're provided - the connection _should_ just fail authentication.
I also don't check the `RequireAuth` property, as we know it is implicitly true in this scenario. If `RequireAuth` is also set to true then the username and password will be applied again (with the same values). Not sure whether this would cause any problems downstream, but I suspect not.

Adds support for elastic cloud ids.

---

src/NLog.Targets.ElasticSearch.Tests/IntegrationTests.cs
src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/ExpandoObjectExtensions.cs
src/NLog.Targets.ElasticSearch/Field.cs
src/NLog.Targets.ElasticSearch/IElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/NLog.Targets.ElasticSearch.csproj

See also: https://github.com/elastic/elasticsearch-net/releases/tag/7.4.2
- Enabled GenerateDocumentationFile and fixed warnings
- Added https://www.nuget.org/packages/Microsoft.SourceLink.GitHub
- Updated NLog + Newtonsoft.Json

Updated Elasticsearch.Net ver. 7.4.2 to fix performance issue

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/FlatObjectContractResolver.cs
src/NLog.Targets.ElasticSearch/ObjectConverter.cs
src/NLog.Targets.ElasticSearch/StringExtensions.cs

Protection again stack-overflow from cyclic references. See also #114 + #109 + #102
New setting `MaxRecursionLimit` to enable safe conversion to ExpandoObject for advanced object-types. Thus avoiding issues with stackoverflow in Elasticsearch.Net.
- `MaxRecursionLimit="-1"` - **Default** Let Elasticsearch.Net handle all the reflection.
- `MaxRecursionLimit="0"` - Perform ToString on everything without doing reflection.
- `MaxRecursionLimit="1"` - Reflection only performed on initial object, where all properties are converted as ToString.
- `MaxRecursionLimit="2"` - Full reflection but with ignore-handling of cyclic references.

ElasticSearchTarget - Added MaxRecursionLimit to prevent Stack-overflow

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs

Fixing Typo. It should be `MemberInfo` (Base-class) and not `MethodInfo`.

feat: skip jsonserialize the entire world when meeting deep reflection types

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/JsonToStringConverter.cs

Trying to resolve #129 when using `MaxRecursionLimit="2"`. Better handling of Microsoft-Logger output on [LogRequestFinished](https://github.com/aspnet/Hosting/blob/f9d145887773e0c650e66165e0c61886153bcc0b/src/Microsoft.AspNetCore.Hosting/Internal/HostingApplicationDiagnostics.cs#L182) in AspNetCore.
Also discovered that `ExpandoObject`-logic doesn't work well with `JsonToStringConverter`. Now changed  `JsonToStringConverter` to generate output for an json-object so it can be converted into `ExpandoObject`:
```
2020-07-09 09:42:56.2691 Error ElasticSearch: Error while formatting property: MethodInfo Exception: System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Dynamic.ExpandoObject'.
at NLog.Targets.ElasticSearch.StringExtensions.ToExpandoObject(Stri …
```

feat: Skip jsonserialize of System.Net.IpAddress since properties throws exceptions

---

src/NLog.Targets.ElasticSearch.Tests/App.config
src/NLog.Targets.ElasticSearch.Tests/IntegrationTests.cs
src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/ObjectTypeConvert.cs

Alternative implementation of #126 that resolves #127
Then you can do this:
```xml
<target xsi:type="ElasticSearch">
<typeconverter objecttype="System.Uri, System.Private.Uri" />
</target>
```

feat: Enable override of jsonserialize for additional object types

---

README.md

make it clear how to set the uri attribute in xml
The first time I try to set the uri, I mistakenly set it on `<target name="elastic" xsi:type="BufferingWrapper" flushTimeout="5000">`

docs: make it clear how to set the uri attribute in xml

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/IElasticSearchTarget.cs

We can use an api token authentication without the cloud connection pool.

feat: add support for api token authentication without cloudId

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/NLog.Targets.ElasticSearch.csproj

In some cases the `BytesResponse` flag Success is not enough to identify a failed index operation. We should rely on the `BulkResponse` that returns the items with errors. 
For example this will not log anything in the internal logger with the current approach:
`Successful (200) low level call on POST: /_bulk
{"took":0,"errors":true,"items":[{"index":{"_index":"logstash-2021.07.12","_type":"_doc","_id":"OTgmmnoBq3Eup03vE24t","status":403,"error":{"type":"security_exception","reason":"action [indices:data/write/bulk[s]] is unauthorized for API key id [NzgjmnoBq3Eup03vg25H] of user [elastic] on indices [logstash-2021.07.12], this action is granted by the index privileges [create_doc,create,delete,index,write,all]"}`
But the `BulkResponse` has the `Errors` flag and will include in this case …

feat: better error handling from server bulk response.

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/IElasticSearchTarget.cs

We have upgraded Elastic server to version 8.1.3 and experienced errors. After reading https://www.elastic.co/guide/en/elasticsearch/client/net-api/7.17/connecting-to-elasticsearch-v8.html#enabling-compatibility-mode and https://github.com/elastic/elasticsearch-net/issues/6154 we tried setting the ELASTIC_CLIENT_APIVERSIONING environment variable which fixed it.
One of our applications, though, connects to two different Elastic servers, one for logging and one for a search index. The search index server is on version 7.10 which does not yet support ApiVersioningHeader, and we cannot upgrade it yet. Thus we need NLog target to run with EnableApiVersioningHeader and the other client without.
This PR adds support for enabling ApiVersioningHeader just for the NLog target from config.
A …

feat: Add support for EnableApiVersioningHeader option for servers v8+

---

src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs

`EnableJsonLayout=true` fails with `NullReferenceException` when not having assigned `pipeline`-property.
Fixing bug introduced with #125, that shows when using NLog 5.0
Resolves  #163

fix: EnableJsonLayout - Ensure valid DocumentInfo when pipeline not assigned

---

src/NLog.Targets.ElasticSearch.Tests/NLog.Targets.ElasticSearch.Tests.csproj
src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/IElasticSearchTarget.cs
src/NLog.Targets.ElasticSearch/NLog.Targets.ElasticSearch.csproj

feat: updated nuget-dependencies and introduced IncludeEventProperties
